package com.controlemployees.controlemployees.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import java.math.BigDecimal

@DynamoDBTable(tableName = "Employee")
data class Employee (
    @DynamoDBHashKey
    var id: String? = null,
    @DynamoDBAttribute
    var name: String? = null ,
    @DynamoDBAttribute
    var doc: String? = null,
    @DynamoDBAttribute
    var sector: String? = null,
    @DynamoDBAttribute
    var salary: BigDecimal? = null): java.io.Serializable {}